### ISSUE TITLE
Can't create Pool at kovan (UNPREDICTABLE_GAS_LIMIT)

### ISSUE THREAD

**Issue by LikoIlya** [balancer-labs/pool-management-vue#232]
### Expected behavior

1. Add tokens and setup pool configs.
2. Approve spending tokens.
3. Create pool.

### Actual behavior

On 3 step when click create none error shown, only errors inside console.

![image](https://user-images.githubusercontent.com/15039930/102713860-a513c100-42d3-11eb-9415-7c20648bff11.png)

> a little bit confused to see my address inside the gasPrice field, is it ok?

### Steps to reproduce the behavior

 Have some freshly created token, add it to the pool

**Comment by jwineman** [comment]
I'm seeing this issue trying to add liquidity to sUSD/sTSLA as well.
