### ISSUE TITLE
Cannot switch to rinkeby test network

### ISSUE THREAD

**Issue by lucasmr** [balancer-labs/pool-management-vue#258]
Hello, I would like to use Rinkeby, but the provided rinkeby.json from their site is not working with pool-management-vue. Any ideas what needs to change in the src/config/ files? The only section that I'm certain is:

```
{
  "network": "rinkeby",
  "chainId": 4,
  "defaultPrecision": 2,
  "explorer": "https://www.rinkeby.io/",
  ...
  ```
  
  Which fields are mandatory, and what needs to be changed?
  
  Thanks!

**Comment by ZhuyichaoCode** [comment]
and BSC testnet
