### ISSUE TITLE
Empty pool page

### ISSUE THREAD

**Issue by farwayer** [balancer-labs/pool-management-vue#288]
### Expected behavior

Pool page

### Actual behavior

Empty pool list

### Steps to reproduce the behavior

![2022_01_28T08 44 57](https://user-images.githubusercontent.com/2343101/151494311-7f37a4b7-cfdd-403d-9a35-3684b7c2401e.png)

**Comment by FernandoMartinelli** [comment]
This should be resolved now. Thanks for spotting and reporting @farwayer !
